languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "NoahCode"
copyright = "© Attribution-NonCommercial-ShareAlike 4.0 International"

[params]
  dateFormat = "2 January 2006"
  description = "NoahCode's personal website about programming, blogging and ..."

[params.author]
  name = "NoahCode"
  image = "img/author.jpg"
  headline = "☠️GG"
  bio = "Programmer | Tech enthusiast"
  links = [
    { email = "mailto:noahcodegg@gmail.com" },
    { github = "https://github.com/NoahCodeGG" },
  ]